import numpy
x=numpy.array([[1,2],[4,5]])
y=numpy.array([[7,8],[9,10]])
print("The element wise addition of matrix is:")
print(numpy.add(x,y))
print("The element wise substraction of matrix is:")
print(numpy.subtract(x,y))
print("The element wise multiplication of matrix is:")
print(numpy.multiply(x,y))
print("The element wise division of matrix is:")
print(numpy.divide(x,y))
print("The transpose of matrix x is:")
print(x.T)
print("The transpose of matrix y is:")
print(y.T)